### PR TITLE
feat(BuyWithMoonPay): Reverse icon and text to match other buttons (#461)

### PR DESCRIPTION
**Pull request by essj**
Issue [#461](https://github.com/binance-chain/ui-project-management/issues/461).

### CODE REVIEW

**Comment by cchungmin** [comment]
Checks failed at Percy :( @essj 
Is it expected? (Space?)

**Review by cchungmin — APPROVED** [review]
👍

**Comment by essj** [comment]
@cchungmin Sorry, I should have waited for the tests to pass before requesting review. Percy tests need to be manually approved, which I've done. 😄

**Comment by cchungmin** [comment]
Cool, good to know!

**Pull request merged**
